### ISSUE TITLE
Can't search for gem level.

### ISSUE THREAD

**Issue by charlarpoe1** [Tonexus/poe-scambot#3]
I've been trying to edit my local copy and can't figure this out.  I want to hit only level 3 or 4 enlighten gems. and i've added the following above the join statement.
 
        for props in item['properties']
            if props['name'] == 'Level':
               gemLevel = props['values'][0][0]

it won't parse :(

**Comment by Tonexus** [comment]
You're missing a semicolon after the for statement. Instead of running the script directly, you can also open command prompt and use the command "python scambot.pyw", which will give you console output if any error occurs and can be used to view any print statements.

**Comment by Haroldyolo** [comment]
Hi charlarpoe1,

Where exactly are you adding this line in order to work? I tried adding it above here:

`full_name = constants.LOCALIZATION.sub('', ' '.join(filter(None, [item['name'], item['typeLine']])))`

but it didn't work for some reason. Can you please help? I would love to look for some gems as well.
